CadastroCliente/urls.py
from django.urls import path
from CadastroCliente import views

urlpatterns = [ 
    path('', views.index, name='index'),
    path('clientes', views.listar_clientes, name='clientes'),
    path('profissoes', views.listar_profissoes, name='profissoes'),
    path('cliente/<int:id>', views.detalhar_cliente, name='detalhar')
]

Cadastros/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CadastroCliente.urls'))    
]

CadastroCliente/models.py
from django.db import models

# Create your models here.
class Profissao(models.Model):
    nome = models.CharField(max_length=30)

    def __str__(self):
        return self.nome
    
    class Meta:
        verbose_name_plural = 'Profissões'

class Interesse(models.Model):
    nome = models.CharField(max_length=20)

    def __str__(self):
        return self.nome

class Cliente(models.Model):
    ESTADO_CIVIL = [
        ('SOL', 'Solteiro'),
        ('CAS', 'Casado'),
        ('DIV', 'Divorciado'),
        ('Viu', 'Viúvo')
        ]
    nome = models.CharField(max_length=50)
    cpf = models.CharField(max_length=14)
    data_nascimento = models.DateField()
    estado_civil = models.CharField(max_length=3, choices=ESTADO_CIVIL, null=True)
    profissao = models.ForeignKey(Profissao, on_delete=models.SET_NULL, null=True, verbose_name='Profissão')
    email = models.EmailField(max_length=120, unique=True)
    endereco = models.CharField(max_length=250, null=True, verbose_name='Endereço')
    nro = models.IntegerField(null=True)
    bairro = models.CharField(max_length=50, null=True)
    cidade = models.CharField(max_length=50, null=True)
    cep = models.CharField(max_length=9, null=True)
    matricula = models.IntegerField(verbose_name='Matrícula')
    renda_mensal = models.DecimalField(max_digits=10, decimal_places=2)
    interesses = models.ManyToManyField(Interesse)
    ativo = models.BooleanField(verbose_name='Usuáro Ativo')
   
    def __str__(self):
        return self.nome
    
class Telefone(models.Model):
    ddd = models.CharField(max_length=2)
    numero = models.CharField(max_length=10)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)

    def __str__(self):
        return f"({self.ddd}) {self.numero}"

CadastroCliente/views.py
from django.shortcuts import render
from CadastroCliente.models import Cliente, Profissao, Telefone


# Create your views here.
def index(request):
    meu_nome = 'Beltrano da Costa'
    lista_frutas = ['Laranja', 'Maça', 'Banana']
    context = {
        'nome': meu_nome,
        'frutas': lista_frutas
        }
    return render(request, 'index.html', context)

def listar_clientes(request):
    # busca todos os clientes cadastrados na tabela (admin)
    lista_clientes = Cliente.objects.all()
    profissoes = Profissao.objects.all()
    # o dicionário (variável) context é que vai mandar para o template
    context = {
        "clientes": lista_clientes,
        "profissoes": profissoes        
    }
    return render(request, 'lista_clientes.html', context)

def listar_profissoes(request):
    profissoes = Profissao.objects.all()
    context = {
        "profissoes": profissoes
    }
    return render(request, 'profissoes.html', context)

def detalhar_cliente(request, id):
    # buscando no banco de dados o cliente pelo id
    cliente = Cliente.objects.get(id = id)
    telefones = Telefone.objects.filter(cliente_id = id)
    context = {
        "cliente": cliente,
        "telefones": telefones
    }
    return render(request, "cliente_detalhes.html", context)

CadastroCliente/templates/cliente_detalhes.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{cliente.nome}}</title>
</head>
<body>
    
    <h1>{{cliente.nome}}</h1>

    <table border="1">
        <tr>
            <td>Nome:</td>
            <td>{{cliente.nome}}</td>
        </tr>
        <tr> 
            <td>Data de Nascimento:</td>
            <td>{{cliente.data_nascimento|date:"d/m/y" }}</td>
        </tr>
        <tr>
            <td>Endereço:</td>
            <td>{{cliente.endereco}}, {{ cliente.nro }} - {{ cliente.bairro }} - {{ cliente.cep }}</td>
        </tr>
        <tr>
            <td>Cpf:</td>
            <td>{{ cliente.cpf }}</td>
        </tr>
        <tr>
            <td>E-mail:</td>
            <td>{{ cliente.email }}</td>
        </tr>
        <tr>
            <td>Matrícula:</td>
            <td>{{ cliente.matricula }}</td>
        </tr>
        <tr>
            <td>Estado Civil:</td>
            <td>{{ cliente.get_estado_civil_display}}</td>
        </tr>
        <tr>
            <td>Profissão:</td>
            <td>{{ cliente.profissao }}</td>
        </tr>
        <tr>
        <td>Interesses:</td>
        <td>{{ cliente.interesses.all|join:", " }}</td>
        </tr>
        <tr>
            <td>Telefones:</td>
            <td>
                {% for tel in telefones %}
                ({{ tel.ddd }}) {{ tel.numero }} <br>
                {% endfor %}
            </td>
        </tr>
    </table>

</body>
</html>

CadastroCliente/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
    
    <link rel="stylesheet" type="text/css" href="{% static '/css/estilos.css' %}">
</head>
<body>
    
    <!-- img no django-->
    <img src="{% static '/img/Logo_senac.jpg' %}">

    <h1>{{nome}}</h1>
    <h2>{{nome}}</h2>
    <h3>{{nome}}</h3>
    <h4>{{nome}}</h4>
    <h5>{{nome}}</h5>
    <h6 class="TextoLaranja">{{nome}}</h6>

    <ul>
        {% for fruta in frutas %}
       <li>{{ fruta }}</li>
       {% endfor %}

    </ul>


</body>
</html>

CadastroCliente/templates/lista_clientes.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clientes</title>
</head>
<body>

    <h1>Clientes Senac - SMP</h1>

    <ul>
        {% for x in clientes %}
        <li><a href="/cliente/{{ x.id }}"> {{ x.nome }}</a> - {{ x.data_nascimento }}</li>
        {% endfor %}
       
    </ul>

    <h2>Profissoes</h2>

    <ul>
        {% for profissao in profissoes %}
        <li>{{ profissao.nome }}</li>
        {% endfor %}
       
    </ul>
    
</body>
</html>

CadastroCliente/templates/profissoes.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profissao</title>
</head>
<body>

    <h1>Profissao</h1>

    <ul>
        {% for profissao in profissoes %}
        <li>{{ profissao.nome }}</li>
        {% endfor %}
       
    </ul>
    
</body>
</html>